language: go

go:
    - 1.2
    - tip

install: make deps
script:
    - go test ./builder-parallels-iso/...
    - go test -race ./builder-parallels-iso/...

matrix:
    allow_failures:
        - go: tip
